/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Destination = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'priceFrom' : IDL.Nat,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'addDestination' : IDL.Func([Destination], [], []),
  'getAllDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
  'getDestinationById' : IDL.Func([IDL.Nat], [Destination], ['query']),
  'getDestinationsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Destination)],
      ['query'],
    ),
  'getFeaturedDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Destination = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'priceFrom' : IDL.Nat,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'addDestination' : IDL.Func([Destination], [], []),
    'getAllDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
    'getDestinationById' : IDL.Func([IDL.Nat], [Destination], ['query']),
    'getDestinationsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Destination)],
        ['query'],
      ),
    'getFeaturedDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };